/**
 * Auto-generated lyrics data from Whisper transcription
 * Generated: 2025-10-23T15:29:49.055333
 */

// Global lyrics data
window.lyricsData = {
  outro: 9.86,
  song_source: "vlad.mp3",
  music_source: "vlad-instrumental.mp3",
  generated_timestamp: "2025-10-23T15:29:49.055333",
  sentences: [
    {
      words: [
        {
          text: "A",
          start_time: 5.82,
          end_time: 6.78,
          target_word: false,
        },
        {
          text: "vampire",
          start_time: 6.78,
          end_time: 7.74,
          target_word: false,
        },
        {
          text: "named",
          start_time: 7.74,
          end_time: 8.16,
          target_word: false,
        },
        {
          text: "Vlad",
          start_time: 8.16,
          end_time: 8.66,
          target_word: false,
        },
        {
          text: "with",
          start_time: 8.66,
          end_time: 9.14,
          target_word: true,
        },
        {
          text: "a",
          start_time: 9.14,
          end_time: 9.36,
          target_word: false,
        },
        {
          text: "cape",
          start_time: 9.36,
          end_time: 9.68,
          target_word: true,
        },
        {
          text: "so",
          start_time: 9.68,
          end_time: 10.16,
          target_word: false,
        },
        {
          text: "wide",
          start_time: 10.16,
          end_time: 10.66,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "Went",
          start_time: 10.66,
          end_time: 11.2,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "Trick",
          start_time: 11.2,
          end_time: 11.88,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "or",
          start_time: 11.88,
          end_time: 12.2,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "treating",
          start_time: 12.2,
          end_time: 12.54,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "on",
          start_time: 12.54,
          end_time: 13.06,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "Halloween",
          start_time: 13.06,
          end_time: 13.7,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "night",
          start_time: 13.7,
          end_time: 14.32,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "With",
          start_time: 14.32,
          end_time: 14.76,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "fangs",
          start_time: 14.76,
          end_time: 15.34,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "that",
          start_time: 15.34,
          end_time: 15.78,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "gleamed",
          start_time: 15.78,
          end_time: 16.4,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "and",
          start_time: 16.4,
          end_time: 16.68,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "eyes",
          start_time: 16.68,
          end_time: 17.26,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "that",
          start_time: 17.26,
          end_time: 17.68,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "shone",
          start_time: 17.68,
          end_time: 18.2,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "He",
          start_time: 18.2,
          end_time: 18.54,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "knocked",
          start_time: 18.54,
          end_time: 19.02,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "on",
          start_time: 19.02,
          end_time: 19.52,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "doors",
          start_time: 19.52,
          end_time: 19.94,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "all",
          start_time: 19.94,
          end_time: 20.54,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "on",
          start_time: 20.54,
          end_time: 20.96,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "his",
          start_time: 20.96,
          end_time: 21.26,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "own",
          start_time: 21.26,
          end_time: 21.92,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "Trick",
          start_time: 21.92,
          end_time: 22.82,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "or",
          start_time: 22.82,
          end_time: 23.32,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "treat",
          start_time: 23.32,
          end_time: 23.68,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "he",
          start_time: 23.68,
          end_time: 24.16,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "said",
          start_time: 24.16,
          end_time: 24.6,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "with",
          start_time: 24.6,
          end_time: 25.0,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "a",
          start_time: 25.0,
          end_time: 25.3,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "grin",
          start_time: 25.3,
          end_time: 25.64,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "And",
          start_time: 25.64,
          end_time: 26.24,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "out",
          start_time: 26.24,
          end_time: 26.66,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "popped",
          start_time: 26.66,
          end_time: 26.96,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "candy",
          start_time: 26.96,
          end_time: 27.82,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "from",
          start_time: 27.82,
          end_time: 28.62,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "the",
          start_time: 28.62,
          end_time: 29.02,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "bins",
          start_time: 29.02,
          end_time: 29.34,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "With",
          start_time: 29.34,
          end_time: 29.64,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "a",
          start_time: 29.64,
          end_time: 30.04,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "thank",
          start_time: 30.04,
          end_time: 30.44,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "you",
          start_time: 30.44,
          end_time: 31.08,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "and",
          start_time: 31.08,
          end_time: 31.56,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "a",
          start_time: 31.56,
          end_time: 31.88,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "bow",
          start_time: 31.88,
          end_time: 32.18,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "so",
          start_time: 32.18,
          end_time: 32.82,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "neat",
          start_time: 32.82,
          end_time: 33.2,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "He",
          start_time: 33.2,
          end_time: 33.62,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "flew",
          start_time: 33.62,
          end_time: 34.22,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "away",
          start_time: 34.22,
          end_time: 35.04,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "on",
          start_time: 35.04,
          end_time: 35.62,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "tiny",
          start_time: 35.62,
          end_time: 36.22,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "feet",
          start_time: 36.22,
          end_time: 36.68,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "No",
          start_time: 36.68,
          end_time: 37.42,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "need",
          start_time: 37.42,
          end_time: 38.0,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "for",
          start_time: 38.0,
          end_time: 38.44,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "blood,",
          start_time: 38.44,
          end_time: 38.84,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "he",
          start_time: 38.88,
          end_time: 39.04,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "just",
          start_time: 39.04,
          end_time: 39.56,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "wanted",
          start_time: 39.56,
          end_time: 40.1,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "sweets",
          start_time: 40.1,
          end_time: 40.68,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "A",
          start_time: 40.68,
          end_time: 41.2,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "real",
          start_time: 41.2,
          end_time: 41.66,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "vampire",
          start_time: 41.66,
          end_time: 42.68,
          confidence: 0.0,
          target_word: true,
        },
        {
          text: "but",
          start_time: 42.68,
          end_time: 43.04,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "not",
          start_time: 43.04,
          end_time: 43.7,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "for",
          start_time: 43.7,
          end_time: 44.06,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "treats",
          start_time: 44.06,
          end_time: 44.44,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "that",
          start_time: 44.44,
          end_time: 45.14,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "bite",
          start_time: 45.14,
          end_time: 46.54,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "So",
          start_time: 47.78,
          end_time: 48.82,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "off",
          start_time: 48.82,
          end_time: 49.36,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "he",
          start_time: 49.36,
          end_time: 49.86,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "flew",
          start_time: 49.86,
          end_time: 50.24,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "with",
          start_time: 50.24,
          end_time: 50.76,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "a",
          start_time: 50.76,
          end_time: 50.98,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "bat's",
          start_time: 50.98,
          end_time: 51.52,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "delight",
          start_time: 51.52,
          end_time: 52.22,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "Ready",
          start_time: 52.22,
          end_time: 53.1,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "to",
          start_time: 53.1,
          end_time: 53.52,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "snack",
          start_time: 53.52,
          end_time: 53.9,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "on",
          start_time: 53.9,
          end_time: 54.42,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "candy",
          start_time: 54.42,
          end_time: 55.02,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "all",
          start_time: 55.02,
          end_time: 55.66,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "night",
          start_time: 55.66,
          end_time: 56.76,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
    {
      words: [
        {
          text: "So",
          start_time: 70.34,
          end_time: 71.42,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "off",
          start_time: 71.42,
          end_time: 71.86,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "he",
          start_time: 71.86,
          end_time: 72.28,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "flew",
          start_time: 72.28,
          end_time: 72.8,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "with",
          start_time: 72.8,
          end_time: 73.28,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "a",
          start_time: 73.28,
          end_time: 73.58,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "bat's",
          start_time: 73.58,
          end_time: 74.12,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "delight",
          start_time: 74.12,
          end_time: 74.68,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "Ready",
          start_time: 74.68,
          end_time: 75.74,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "to",
          start_time: 75.74,
          end_time: 76.14,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "snack",
          start_time: 76.14,
          end_time: 76.54,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "on",
          start_time: 76.54,
          end_time: 77.08,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "candy",
          start_time: 77.08,
          end_time: 77.86,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "all",
          start_time: 77.86,
          end_time: 78.56,
          confidence: 0.0,
          target_word: false,
        },
        {
          text: "night",
          start_time: 78.56,
          end_time: 79.48,
          confidence: 0.0,
          target_word: false,
        },
      ],
    },
  ],
};
