/**
 * Golden - Lyrics Data
 * Contains timing, recognition flags, and audio source information
 */

// Global lyrics data for the Golden karaoke game
window.lyricsData = {
  offset: 16.0,
  outro: 3,
  song_1_source: "song.mp3",
  music_source: "music.mp3",
  sentences: [
    {
      words: [
        { text: "I", duration: 0.2, recognise: false },
        { text: "was", duration: 0.2, recognise: false },
        { text: "a", duration: 0.2, recognise: false },
        { text: "ghost,", duration: 0.32, recognise: true },
        { text: "I", duration: 0.2, recognise: false },
        { text: "was", duration: 0.2, recognise: false },
        { text: "alone", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "ha", duration: 1.3, recognise: true },
      ],
    },
    {
      words: [
        { text: "Given", duration: 1.0, recognise: false },
        { text: "the", duration: 1.0, recognise: false },
        { text: "throne,", duration: 1.0, recognise: true },
        { text: "I", duration: 0.2, recognise: false },
        { text: "didn't", duration: 1.0, recognise: false },
        { text: "know", duration: 1.0, recognise: true },
        { text: "how", duration: 1.0, recognise: false },
        { text: "to", duration: 0.2, recognise: false },
        { text: "believe", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "I", duration: 0.2, recognise: false },
        { text: "was", duration: 0.2, recognise: false },
        { text: "the", duration: 1.0, recognise: false },
        { text: "queen", duration: 1.0, recognise: true },
        { text: "that", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "meant", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "I", duration: 0.2, recognise: false },
        { text: "lived", duration: 1.0, recognise: true },
        { text: "two", duration: 1.0, recognise: false },
        { text: "lives,", duration: 1.0, recognise: true },
        { text: "tried", duration: 1.0, recognise: false },
        { text: "to", duration: 0.2, recognise: false },
        { text: "play", duration: 1.0, recognise: true },
        { text: "both", duration: 1.0, recognise: false },
        { text: "sides", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "But", duration: 1.0, recognise: false },
        { text: "I", duration: 0.2, recognise: false },
        { text: "couldn't", duration: 1.0, recognise: true },
        { text: "find", duration: 1.0, recognise: false },
        { text: "my", duration: 1.0, recognise: false },
        { text: "own", duration: 1.0, recognise: true },
        { text: "place", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Called", duration: 1.0, recognise: false },
        { text: "a", duration: 1.0, recognise: false },
        { text: "problem", duration: 1.0, recognise: true },
        { text: "child", duration: 1.0, recognise: true },
        { text: "'cause", duration: 1.0, recognise: false },
        { text: "I", duration: 0.2, recognise: false },
        { text: "got", duration: 1.0, recognise: false },
        { text: "too", duration: 1.0, recognise: false },
        { text: "wild", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "But", duration: 1.0, recognise: false },
        { text: "now", duration: 1.0, recognise: true },
        { text: "that's", duration: 1.0, recognise: false },
        { text: "how", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "getting", duration: 1.0, recognise: true },
        { text: "paid", duration: 1.0, recognise: true },
        { text: "on", duration: 1.0, recognise: false },
        { text: "stage", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "done", duration: 1.0, recognise: true },
        { text: "hidin',", duration: 1.0, recognise: true },
        { text: "now", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "shinin'", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "We", duration: 1.0, recognise: false },
        { text: "dreamin'", duration: 1.0, recognise: true },
        { text: "hard,", duration: 1.0, recognise: false },
        { text: "we", duration: 1.0, recognise: false },
        { text: "came", duration: 1.0, recognise: true },
        { text: "so", duration: 1.0, recognise: false },
        { text: "far,", duration: 1.0, recognise: true },
        { text: "now", duration: 1.0, recognise: false },
        { text: "I'll", duration: 1.0, recognise: false },
        { text: "believe", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "We're", duration: 1.0, recognise: false },
        { text: "goin'", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "it's", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "moment", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "You", duration: 1.0, recognise: false },
        { text: "know", duration: 1.0, recognise: false },
        { text: "together", duration: 1.0, recognise: true },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "glowing", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
        { text: "golden", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up", duration: 1.0, recognise: true },
        { text: "with", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "voices", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
        { text: "golden", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "done", duration: 1.0, recognise: true },
        { text: "hidin',", duration: 1.0, recognise: true },
        { text: "now", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "shinin'", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "time,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "fears,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "lies", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "That's", duration: 1.0, recognise: false },
        { text: "who", duration: 1.0, recognise: false },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Waited", duration: 1.0, recognise: true },
        { text: "so", duration: 1.0, recognise: false },
        { text: "long", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "break", duration: 1.0, recognise: true },
        { text: "these", duration: 1.0, recognise: false },
        { text: "walls", duration: 1.0, recognise: true },
        { text: "down", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "to", duration: 0.2, recognise: false },
        { text: "wake", duration: 1.0, recognise: true },
        { text: "up", duration: 1.0, recognise: false },
        { text: "and", duration: 1.0, recognise: false },
        { text: "feel", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "me", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Put", duration: 1.0, recognise: false },
        { text: "these", duration: 1.0, recognise: false },
        { text: "patterns", duration: 1.0, recognise: true },
        { text: "all", duration: 1.0, recognise: false },
        { text: "in", duration: 1.0, recognise: false },
        { text: "the", duration: 1.0, recognise: false },
        { text: "past", duration: 1.0, recognise: true },
        { text: "now", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "And", duration: 1.0, recognise: false },
        { text: "finally", duration: 1.0, recognise: true },
        { text: "live", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "the", duration: 1.0, recognise: false },
        { text: "girl", duration: 1.0, recognise: true },
        { text: "they", duration: 1.0, recognise: false },
        { text: "all", duration: 1.0, recognise: false },
        { text: "see", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "No", duration: 1.0, recognise: false },
        { text: "more", duration: 1.0, recognise: false },
        { text: "hiding,", duration: 1.0, recognise: true },
        { text: "I'll", duration: 1.0, recognise: false },
        { text: "be", duration: 1.0, recognise: false },
        { text: "shining", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "'Cause", duration: 1.0, recognise: false },
        { text: "we", duration: 1.0, recognise: false },
        { text: "are", duration: 1.0, recognise: false },
        { text: "hunters,", duration: 1.0, recognise: true },
        { text: "voices", duration: 1.0, recognise: true },
        { text: "strong,", duration: 1.0, recognise: true },
        { text: "and", duration: 1.0, recognise: false },
        { text: "I", duration: 0.2, recognise: false },
        { text: "know", duration: 1.0, recognise: false },
        { text: "I'll", duration: 1.0, recognise: false },
        { text: "believe", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "We're", duration: 1.0, recognise: false },
        { text: "goin'", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "it's", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "moment", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "You", duration: 1.0, recognise: false },
        { text: "know", duration: 1.0, recognise: false },
        { text: "together", duration: 1.0, recognise: true },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "glowing", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
        { text: "golden", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "up,", duration: 1.0, recognise: true },
        { text: "with", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "voices", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
        { text: "golden", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "done", duration: 1.0, recognise: true },
        { text: "hidin',", duration: 1.0, recognise: true },
        { text: "now", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "shining", duration: 1.0, recognise: true },
        { text: "like", duration: 1.0, recognise: false },
        { text: "I'm", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "Oh,", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "time,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "fears,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "lies", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "That's", duration: 1.0, recognise: false },
        { text: "who", duration: 1.0, recognise: false },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "You", duration: 1.0, recognise: false },
        { text: "know", duration: 1.0, recognise: false },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
        { text: "golden", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "We're", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "gonna", duration: 1.0, recognise: true },
        { text: "be", duration: 1.0, recognise: false },
      ],
    },
    {
      words: [
        { text: "Born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be,", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: false },
        { text: "glowin'", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "You", duration: 1.0, recognise: false },
        { text: "know", duration: 1.0, recognise: false },
        { text: "that", duration: 1.0, recognise: false },
        { text: "it's", duration: 1.0, recognise: false },
        { text: "our", duration: 1.0, recognise: false },
        { text: "time,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "fears,", duration: 1.0, recognise: true },
        { text: "no", duration: 1.0, recognise: false },
        { text: "lies", duration: 1.0, recognise: true },
      ],
    },
    {
      words: [
        { text: "That's", duration: 1.0, recognise: false },
        { text: "who", duration: 1.0, recognise: false },
        { text: "we're", duration: 1.0, recognise: false },
        { text: "born", duration: 1.0, recognise: true },
        { text: "to", duration: 0.2, recognise: false },
        { text: "be", duration: 1.0, recognise: true },
      ],
    },
  ],
};
